apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp-service.fullname" . }}
  labels:
    {{- include "sftp-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sftp-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: sftp
      port: {{ .Values.service.port }}
      targetPort: sftp
      protocol: TCP

    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}

